{
 "title": "Dashboard",
 "time": { "from": "2026-03-10T20:58:18.589Z", "to": "2026-03-11T20:58:18.589Z" },
 "panels": [
  {
   "title": "Durée du backup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "backup_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dernière sauvegarde",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_success_timestamp * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Intégrité",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "backup_integrity_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Taille du snapshot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "backup_snapshot_size_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}